export const RECOMMENDATION_TYPES = {
  EXPENSE_CONTROL: 'EXPENSE_CONTROL',
  LIQUIDITY_FIRST: 'LIQUIDITY_FIRST',
  STABLE_SAVING: 'STABLE_SAVING',
  BALANCED_SAVING: 'BALANCED_SAVING',
  DIVERSIFIED_ALLOCATION: 'DIVERSIFIED_ALLOCATION',
} as const;

export type RecommendationType =
  (typeof RECOMMENDATION_TYPES)[keyof typeof RECOMMENDATION_TYPES];
