export const SAVING_GOALS = {
  EMERGENCY_FUND: 'EMERGENCY_FUND',
  LIFE_STABILITY: 'LIFE_STABILITY',
  TRAVEL: 'TRAVEL',
  HOUSING_MARRIAGE: 'HOUSING_MARRIAGE',
  INVESTMENT_PREP: 'INVESTMENT_PREP',
} as const;

export type SavingGoal = (typeof SAVING_GOALS)[keyof typeof SAVING_GOALS];
